import type { ProviderDescriptor } from './types/provider-descriptor.js';

export const BUILTIN_PROVIDERS: ProviderDescriptor[] = [
  // === Core AI Companies ===
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'OPENAI_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    pricingUrl: 'https://openai.com/api/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.deepseek.com',
    defaultModel: 'deepseek-v4-flash',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'DEEPSEEK_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://deepseek.com',
    docsUrl: 'https://api-docs.deepseek.com',
    pricingUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
    isFree: false,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'mistral-large-latest',
    capabilities: ['chat', 'embeddings', 'vision', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'MISTRAL_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    pricingUrl: 'https://mistral.ai/products/la-plateforme#pricing',
    isFree: false,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.x.ai/v1',
    defaultModel: 'grok-4.5',
    capabilities: ['chat', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'XAI_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://x.ai',
    docsUrl: 'https://docs.x.ai',
    pricingUrl: 'https://x.ai/api',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.perplexity.ai',
    defaultModel: 'sonar-pro',
    capabilities: ['chat', 'embeddings', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'PERPLEXITY_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    pricingUrl: 'https://docs.perplexity.ai/guides/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    category: 'core-ai',
    protocols: ['openai-chat', 'google-gemini'],
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    defaultModel: 'gemini-2.5-flash',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'header', headerName: 'x-goog-api-key', envVar: 'GEMINI_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://ai.google.dev',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    pricingUrl: 'https://ai.google.dev/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.cohere.com/v1',
    defaultModel: 'command-a-plus-05-2026',
    capabilities: ['chat', 'embeddings', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'COHERE_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    pricingUrl: 'https://cohere.com/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },

  // === Inference Platforms ===
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'openai/gpt-4o',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'OPENROUTER_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://openrouter.ai',
    docsUrl: 'https://openrouter.ai/docs',
    pricingUrl: 'https://openrouter.ai/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'together',
    name: 'Together AI',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.together.xyz/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'TOGETHER_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://together.ai',
    docsUrl: 'https://docs.together.ai',
    pricingUrl: 'https://together.ai/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'llama-3.3-70b-versatile',
    capabilities: ['chat', 'vision', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'GROQ_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    pricingUrl: 'https://console.groq.com/docs/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    defaultModel: 'accounts/fireworks/models/deepseek-v3p1',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'FIREWORKS_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://fireworks.ai',
    docsUrl: 'https://docs.fireworks.ai',
    pricingUrl: 'https://fireworks.ai/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://models.github.ai',
    defaultModel: 'gpt-4o',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'GITHUB_TOKEN' },
    adapterType: 'openai-compatible',
    website: 'https://github.com/marketplace/models',
    docsUrl: 'https://docs.github.com/en/github-models',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'meta/llama-3.1-8b-instruct',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'NVIDIA_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://nvidia.com/nim',
    docsUrl: 'https://build.nvidia.com/docs',
    pricingUrl: 'https://build.nvidia.com/pricing',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: false,
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'DEEPINFRA_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://deepinfra.com',
    docsUrl: 'https://deepinfra.com/docs',
    pricingUrl: 'https://deepinfra.com/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.cerebras.ai/v1',
    defaultModel: 'llama-3.3-70b',
    capabilities: ['chat', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'CEREBRAS_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://cerebras.ai',
    docsUrl: 'https://inference-docs.cerebras.ai',
    pricingUrl: 'https://cerebras.ai/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.sambanova.ai/v1',
    defaultModel: 'Meta-Llama-3.3-70B-Instruct',
    capabilities: ['chat', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'SAMBANOVA_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://sambanova.ai',
    docsUrl: 'https://docs.sambanova.ai',
    pricingUrl: 'https://sambanova.ai/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },

  // === Chinese Providers ===
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModel: 'GLM-5.1',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'ZHIPU_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://zhipu.ai',
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    pricingUrl: 'https://open.bigmodel.cn/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'MiniMax-M3',
    capabilities: ['chat', 'embeddings', 'vision', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'MINIMAX_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://minimax.io',
    docsUrl: 'https://platform.minimax.io/docs',
    pricingUrl: 'https://platform.minimax.io/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.moonshot.cn/v1',
    defaultModel: 'moonshot-v1-8k',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'MOONSHOT_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://moonshot.cn',
    docsUrl: 'https://platform.moonshot.cn/docs',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'qwen',
    name: 'Alibaba Qwen',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModel: 'qwen-plus',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'QWEN_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://tongyi.aliyun.com',
    docsUrl: 'https://help.aliyun.com/zh/model-studio',
    pricingUrl: 'https://help.aliyun.com/zh/model-studio/pricing',
    isFree: false,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'hunyuan',
    name: 'Tencent Hunyuan',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    defaultModel: 'hunyuan-pro',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'HUNYUAN_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://hunyuan.tencent.com',
    docsUrl: 'https://cloud.tencent.com/document/product/1729',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'yi',
    name: '01.AI (Yi)',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    defaultModel: 'yi-lightning',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'YI_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://01.ai',
    docsUrl: 'https://platform.lingyiwanwu.com/docs',
    isFree: false,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'ai21',
    name: 'AI21 Labs (Jamba)',
    category: 'core-ai',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.ai21.com/studio/v1',
    defaultModel: 'jamba-1.5-large',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'AI21_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://ai21.com',
    docsUrl: 'https://docs.ai21.com',
    pricingUrl: 'https://www.ai21.com/pricing',
    isFree: false,
    isSelfHostable: true,
    isOpenSource: true,
  },

  // === Local/OpenAI-Compatible ===
  {
    id: 'ollama',
    name: 'Ollama',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:11434/v1',
    defaultModel: 'llama3.2',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'none' },
    adapterType: 'openai-compatible',
    website: 'https://ollama.ai',
    docsUrl: 'https://github.com/ollama/ollama/tree/main/docs',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:1234/v1',
    defaultModel: 'local-model',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'none' },
    adapterType: 'openai-compatible',
    website: 'https://lmstudio.ai',
    docsUrl: 'https://lmstudio.ai/docs',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: false,
  },
  {
    id: 'vllm',
    name: 'vLLM',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:8000/v1',
    defaultModel: 'default',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'none' },
    adapterType: 'openai-compatible',
    website: 'https://vllm.ai',
    docsUrl: 'https://docs.vllm.ai',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'litellm',
    name: 'LiteLLM',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:4000',
    defaultModel: 'gpt-4o',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'LITELLM_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://litellm.ai',
    docsUrl: 'https://docs.litellm.ai',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'localai',
    name: 'LocalAI',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:8080/v1',
    defaultModel: 'default',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'none' },
    adapterType: 'openai-compatible',
    website: 'https://localai.io',
    docsUrl: 'https://localai.io/docs',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'tgi',
    name: 'Text Generation Inference',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:8080',
    defaultModel: 'default',
    capabilities: ['chat', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'none' },
    adapterType: 'openai-compatible',
    website: 'https://huggingface.co/docs/text-generation-inference',
    docsUrl: 'https://huggingface.co/docs/text-generation-inference',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: true,
  },
  {
    id: 'jan',
    name: 'Jan AI',
    category: 'local-server',
    protocols: ['openai-chat'],
    baseUrl: 'http://localhost:1337/v1',
    defaultModel: 'default',
    capabilities: ['chat', 'embeddings', 'vision', 'streaming', 'tools'],
    authType: { type: 'none' },
    adapterType: 'openai-compatible',
    website: 'https://jan.ai',
    docsUrl: 'https://jan.ai/docs',
    isFree: true,
    isSelfHostable: true,
    isOpenSource: true,
  },

  // === Cloud Providers ===
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    category: 'cloud-provider',
    protocols: ['openai-chat'],
    baseUrl: 'https://{resource}.openai.azure.com/openai/deployments/{deployment-id}',
    defaultModel: 'gpt-4o',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'AZURE_OPENAI_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://azure.microsoft.com/products/ai-services/openai-service',
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai',
    pricingUrl: 'https://azure.microsoft.com/pricing/details/cognitive-services/openai-service',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'aws-bedrock',
    name: 'Amazon Bedrock',
    category: 'cloud-provider',
    protocols: ['openai-chat'],
    baseUrl: 'https://bedrock-runtime.{region}.amazonaws.com',
    defaultModel: 'anthropic.claude-sonnet-4-20250514',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'aws-sigv4', service: 'bedrock', region: 'us-east-1' },
    adapterType: 'openai-compatible',
    website: 'https://aws.amazon.com/bedrock',
    docsUrl: 'https://docs.aws.amazon.com/bedrock',
    pricingUrl: 'https://aws.amazon.com/bedrock/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'vertex-ai',
    name: 'Google Vertex AI',
    category: 'cloud-provider',
    protocols: ['openai-chat', 'google-gemini'],
    baseUrl: 'https://{region}-aiplatform.googleapis.com/v1',
    defaultModel: 'gemini-2.5-pro',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'oauth', authUrl: '', tokenUrl: '', scopes: ['https://www.googleapis.com/auth/cloud-platform'] },
    adapterType: 'openai-compatible',
    website: 'https://cloud.google.com/vertex-ai',
    docsUrl: 'https://cloud.google.com/vertex-ai/docs',
    pricingUrl: 'https://cloud.google.com/vertex-ai/generative-ai/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI',
    category: 'cloud-provider',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1',
    defaultModel: '@cf/meta/llama-3.3-70b-instruct',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'audio', 'streaming'],
    authType: { type: 'bearer', envVar: 'CLOUDFLARE_API_TOKEN' },
    adapterType: 'openai-compatible',
    website: 'https://cloudflare.com/ai',
    docsUrl: 'https://developers.cloudflare.com/workers-ai',
    pricingUrl: 'https://developers.cloudflare.com/workers-ai/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    category: 'cloud-provider',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.studio.nebius.ai/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'NEBIUS_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://nebius.com/studio',
    docsUrl: 'https://docs.nebius.com/studio',
    pricingUrl: 'https://nebius.com/studio/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.hyperbolic.xyz/v1',
    defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct',
    capabilities: ['chat', 'vision', 'image-generation', 'streaming', 'tools'],
    authType: { type: 'bearer', envVar: 'HYPERBOLIC_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://hyperbolic.xyz',
    docsUrl: 'https://docs.hyperbolic.xyz',
    pricingUrl: 'https://hyperbolic.xyz/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'novita',
    name: 'Novita AI',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.novita.ai/v3/openai',
    defaultModel: 'meta-llama/llama-3.1-8b-instruct',
    capabilities: ['chat', 'embeddings', 'vision', 'image-generation', 'streaming', 'tools'],
    authType: { type: 'bearer', envVar: 'NOVITA_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://novita.ai',
    docsUrl: 'https://docs.novita.ai',
    pricingUrl: 'https://novita.ai/pricing',
    isFree: false,
    isSelfHostable: false,
    isOpenSource: false,
  },
  {
    id: 'featherless',
    name: 'Featherless AI',
    category: 'inference-platform',
    protocols: ['openai-chat'],
    baseUrl: 'https://api.featherless.ai/v1',
    defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct',
    capabilities: ['chat', 'vision', 'streaming', 'tools', 'structured-output'],
    authType: { type: 'bearer', envVar: 'FEATHERLESS_API_KEY' },
    adapterType: 'openai-compatible',
    website: 'https://featherless.ai',
    docsUrl: 'https://docs.featherless.ai',
    pricingUrl: 'https://featherless.ai/pricing',
    isFree: true,
    isSelfHostable: false,
    isOpenSource: false,
  },
];

export function getAllDescriptors(): ProviderDescriptor[] {
  return [...BUILTIN_PROVIDERS];
}

export function getDescriptor(id: string): ProviderDescriptor | undefined {
  return BUILTIN_PROVIDERS.find((p) => p.id === id);
}

export function getOpenAICompatibleDescriptors(): ProviderDescriptor[] {
  return BUILTIN_PROVIDERS.filter((p) => p.adapterType === 'openai-compatible');
}

export function getFreeProviders(): ProviderDescriptor[] {
  return BUILTIN_PROVIDERS.filter((p) => p.isFree);
}
